config/routes.rb
Kuikui3::Application.routes.draw do
  resources :messages

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  attr_accessible :comment

  validates_presence_of :comment
  validate :message_id_exist

  def message_id_exist
    unless message_id
      errors.add(:message_id, "foreign key can't be blank")
      return false
    end

    begin
      Message.find(self.message_id)
    rescue ActiveRecord::RecordNotFound
      errors.add(:message_id, "foreign key must exist")
      return false
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  has_many :comments
  attr_accessible :content, :tags
  validates_presence_of :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @message = Message.new
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])
    @comments = @message.comments

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @messages = Message.all

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_url, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Kuikui3" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Kuikui3</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message, :html => { :class => 'form-horizontal new-message' } do |f| %>
  <%= f.text_area :content, :class => 'text_area span6', :rows => 3, :placeholder => 'Say something' %>
  <%= f.text_field :tags, :class => 'text_field span6', :placeholder => 'tags' %><br/>

  <%= f.submit nil, :class => 'btn btn-primary' %>

<% end %>

app/views/messages/_message.html.erb
<div class="row message">
  <div class="span1 photo">
    <%= image_tag "http://www.gravatar.com/avatar/ee8ea294c76022c5a6e163a05d255700.png" %>
  </div>
  <div class="span5">
    <div class="row">
      <div class="span4">
        <strong>
          <%#= message.user_name %>
          Apirak
        </strong>
        <%= time_ago_in_words(message.created_at) %>
      </div>
      <div class="span1">
        <%= link_to raw("<i class='icon-pencil'></i>"), edit_message_path(message) %>
        <%= link_to raw("<i class='icon-trash'></i>"), message_path(message), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
    <div class="row">
      <div class="span5">
        <%= link_to message.content, message_path(message), :class => "message-content" %>
      </div>
    </div>
    <div class="row">
      <div class="span5 message-tags">
        <%= message.tags %>
        <%#= show_tag(message) %>
      </div>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/messages/index.html.erb
<%- model_class = Message -%>
<h1>What's happening ?</h1>
<br/>

<%= render :partial => 'form' %>

<% @messages.each do |message| %>
  <%= render :partial => "message", :locals => {:message => message} %>
<% end %>

app/views/messages/new.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/messages/show.html.erb
<%= render :partial => "message", :locals => {:message => @message} %>

<h3>comment</h3>
<p>
<% @comments.each do |comment| -%>
  <div class="row comment">
    <div class="span1 photo">
      <%= image_tag "http://www.gravatar.com/avatar/ee8ea294c76022c5a6e163a05d255700.png" %>
    </div>
    <div class="span5">
      <div class="row">
        <div class="span4">
          <strong>
            <%#= comment.user_name %>
          </strong>
          <%= time_ago_in_words(comment.created_at) %>
        </div>
        <div class="span1">
          <%#= link_to raw("<i class='icon-trash'></i>"), comment, :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
        </div>
      </div>
      <div class="row">
        <div class="span5 message-comment">
          <%= comment.comment %>
        </div>
      </div>
    </div>
  </div>  
<% end -%>
</p>